apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: block-critical-vulnerabilities
spec:
  rules:
    - name: check-vulnerability-scan
      match:
        any:
        - resources:
            kinds: [Pod]
      validate:
        message: "Image has critical vulnerabilities and cannot be deployed."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                all:
                - key: "{{ image_vulnerabilities(element.image).critical }}"
                  operator: GreaterThan
                  value: 0
